"""Init

Revision ID: cef1e4ff4dda
Revises: 
Create Date: 2024-11-11 21:46:31.744143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cef1e4ff4dda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('referral_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix__users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix__users_identity'), 'users', ['identity'], unique=True)
    op.create_index(op.f('ix__users_referral_id'), 'users', ['referral_id'], unique=False)
    op.create_table('referrers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('until_at', postgresql.TIMESTAMP(), server_default=sa.text("now() + interval '14 days'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__referrers__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__referrers'))
    )
    op.create_index(op.f('ix__referrers_id'), 'referrers', ['id'], unique=False)
    op.create_index(op.f('ix__referrers_referrer_id'), 'referrers', ['referrer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__referrers_referrer_id'), table_name='referrers')
    op.drop_index(op.f('ix__referrers_id'), table_name='referrers')
    op.drop_table('referrers')
    op.drop_index(op.f('ix__users_referral_id'), table_name='users')
    op.drop_index(op.f('ix__users_identity'), table_name='users')
    op.drop_index(op.f('ix__users_id'), table_name='users')
    op.drop_index(op.f('ix__users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
